### ISSUE TITLE
Practica5_IrvingFernando

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-IrvingFernand0#3]
[practica5_4US-IrvingFernando.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-IrvingFernand0/files/8874066/practica5_4US-IrvingFernando.pdf)

**Comment by g00gle2401** [comment]
Calificación: 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
